version: '1.2-git-{build}'
skip_tags: true
image: 'Visual Studio 2015'
clone_depth: 1

# Build configuration
configuration:
  - Release

# Branches to build
branches:
  only:
    - master
    - /v\d.*/

# Environment
environment:
  PYTHON: 'C:\Python36-x64'
  NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip
  QTDIR: 'C:\Qt\5.10.0\msvc2015_64'
  QT32PATH: 'C:\Qt\5.10.0\msvc2015'
  QT64PATH: 'C:\Qt\5.10.0\msvc2015_64'
  VSVARSALLPATH: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
  matrix:
    # Build: qmake vs2015 x86 shared
    - BITS: 32
      QMAKE: 1
    # Build: qmake vs2015 x64 shared
    - BITS: 64
      QMAKE: 1
    # Build: meson ninja x64 static
    - BITS: 64
      ARCH: x64
      MESON: 1
      BACKEND: ninja

install:
  - cmd: set "PATH=%PYTHON%;%PATH%"
  # Artifacts
  - cmd: if defined MESON ( set "ARTIFACT_NAME=Cutter%BITS%_static" ) else ( set "ARTIFACT_NAME=Cutter%BITS%" )
  - cmd: if defined MESON ( set "ARTIFACT=dist%BITS%" ) else ( set "ARTIFACT=build%BITS%\cutter%BITS%" )
  # Meson specific
  - cmd: if defined MESON ( if "%ARCH%" == "x64" ( set "PATH=%QT64PATH%\bin;%PATH%" ) else ( set "PATH=%QT32PATH%\bin;%PATH%" ) )
  - cmd: if defined MESON ( python -m pip install meson )
  - cmd: if defined MESON ( if "%BACKEND%" == "ninja" ( powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; wget %NINJA_URL% -OutFile ninja.zip" && unzip ninja.zip ) )

before_build:
  - cmd: if defined QMAKE ( prepare_r2.bat %BITS% )
  - cmd: if defined MESON ( git submodule update --init )

# Build config
build_script:
  - cmd: if defined QMAKE ( build.bat %BITS% )
  - cmd: if defined MESON ( call "%VSVARSALLPATH%" %ARCH% && python meson.py --dist=%ARTIFACT% --backend=%BACKEND% )

# Tests
test: off

# Artifacts
artifacts:
  - path: "%ARTIFACT%"
    name: "%ARTIFACT_NAME%"

deploy:
  release: cutter-$(appveyor_build_version)
  description: 'Cutter binaries (Windows)'
  provider: GitHub
  auth_token:
    secure: 2SmsqS2RaX2N5c9UwUcfBwNmMX64FfPAZFShLyxIkZXiC8vLaYCHToWxBYEuWRSk
  artifact: Cutter%BITS%
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true
